[package]
name = "rust_core_mesh"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
thiserror = "1"

[dev-dependencies]
ndarray = "0.15"
